<script setup>import TwinalyzeAnalytics from '@twinalyze/web-analytics';import {useRouter} from 'vue-router';
import {useCart} from '../stores/cart';const router=useRouter(),cart=useCart();
const checkout=()=>{TwinalyzeAnalytics.track('beginCheckout',
{cartValue:cart.subtotal.value,
totalQuantity:cart.count.value,
itemTypes:cart.items.value.length,
currency:'USD',
source:'nivora_vue_npm_store'})
;router.push('/checkout');};</script>
<template><section class="page"><span>NIVORA BAG</span><h1>Your selected objects.</h1><div v-if="cart.items.value.length" class="layout"><div><article v-for="item in cart.items.value" :key="item.product.id"><div class="thumb" :class="item.product.tone">{{item.product.symbol}}</div><div><small>{{item.product.category}}</small><h2>{{item.product.name}}</h2><strong>${{item.product.price}}</strong></div><div class="qty"><button @click="cart.setQuantity(item.product.id,item.quantity-1)">−</button><span>{{item.quantity}}</span><button @click="cart.setQuantity(item.product.id,item.quantity+1)">+</button></div><button class="remove" @click="cart.remove(item.product.id)">Remove</button></article></div><aside><span>ORDER SUMMARY</span><div><p>Subtotal</p><strong>${{cart.subtotal.value}}</strong></div><div><p>Delivery</p><strong>Free</strong></div><div class="total"><p>Total</p><strong>${{cart.subtotal.value}}</strong></div><button @click="checkout">Continue to checkout</button></aside></div><div v-else class="empty"><span>○</span><h2>Your bag is empty.</h2><RouterLink class="solid-button" to="/products">Browse collection</RouterLink></div></section></template>
<style scoped>.page{padding:70px 6vw}.page>span,aside>span{color:var(--coral-dark);font-size:10px;font-weight:900;letter-spacing:.18em}h1{margin:12px 0 40px;font:400 clamp(56px,7vw,90px)/.92 Georgia}.layout{display:grid;grid-template-columns:1fr 390px;gap:42px;align-items:start}article{padding:18px 0;display:grid;grid-template-columns:105px 1fr auto auto;gap:18px;align-items:center;border-bottom:1px solid var(--line)}.thumb{width:105px;height:105px;display:grid;place-items:center;border-radius:22px;font:400 50px Georgia}.peach{background:#f2c5aa}.mint{background:#b8d8ca}.sky{background:#bdd7e7}.lilac{background:#d4c6dd}.sand{background:#dfcfaa}.rose{background:#e8bcc3}.blue{background:#aebfd8}.green{background:#b9cca5}article small{color:var(--muted);text-transform:uppercase}article h2{margin:6px 0 10px;font:400 24px Georgia}.qty{display:flex;align-items:center;border:1px solid var(--line);border-radius:999px}.qty button{width:36px;height:36px;border:0;background:transparent}.remove{border:0;background:transparent;color:#a63e2c}aside{position:sticky;top:120px;padding:28px;border-radius:28px;background:var(--cream)}aside div{display:flex;justify-content:space-between;border-bottom:1px solid var(--line)}aside .total{border:0;font-size:20px}aside>button{width:100%;margin-top:18px;padding:15px;border:0;border-radius:999px;background:var(--ink);color:white;font-weight:900}.empty{padding:90px;text-align:center;border:1px dashed var(--line);border-radius:30px}.empty>span{font:400 100px Georgia}.empty h2{font:400 42px Georgia}@media(max-width:900px){.layout{grid-template-columns:1fr}aside{position:static}}@media(max-width:620px){.page{padding-inline:20px}article{grid-template-columns:82px 1fr}.thumb{width:82px;height:82px}.qty,.remove{grid-column:2;justify-self:start}}</style>
